# Generated by Django 3.2.19 on 2023-05-28 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('tipo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epeun.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('tipou', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idregistro', models.AutoField(primary_key=True, serialize=False)),
                ('nombreregistro', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epeun.causa')),
                ('tipoU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epeun.universidad')),
            ],
        ),
        migrations.CreateModel(
            name='Efecto',
            fields=[
                ('idefecto', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epeun.causa')),
            ],
        ),
    ]
