# Generated by Django 3.2.19 on 2023-06-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epeun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efecto',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
