# Generated by Django 3.2.19 on 2023-06-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epeun', '0002_alter_efecto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efecto',
            name='tema',
            field=models.CharField(max_length=100),
        ),
    ]
